name: Runs bot on merge and PR
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  
jobs:
  cancel:
    name: 'Cancel Other Workflow'
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}
          
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.5
      - name: decrypt
        env:
          SECRET_PASSPHRASE: ${{secrets.SECRET_PASSPHRASE}}
        run: |
          mkdir secrets
          gpg --decrypt --quiet --batch --yes --passphrase="$SECRET_PASSPHRASE" --output $HOME/runner/secrets/bot_token.json secrets_encrypted/bot_token.json.gpg
          echo $HOME/secrets/bot_token.json
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # - name: run script 
        # run: python -u telegram-bot.py
