name: Runs bot on merge and PR
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.5
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-telegram-bot

      - name: run script
        run: python -u telegram-bot.py