name: Runs bot on merge and PR
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.5
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: run script 1st time
        run: python -u telegram-bot.py

      - name: run script 2nd time
        run: python -u telegram-bot.py

      - name: run script 3rd time
        run: python -u telegram-bot.py

      - name: run script 4th time
        run: python -u telegram-bot.py
